### ISSUE TITLE
Fail to generate kubectl docs

### ISSUE THREAD

**Issue by supereagle** [kubernetes-incubator/reference-docs#16]
As I need to update the kubectl docs in [k8s io PR 3540](https://github.com/kubernetes/kubernetes.github.io/pull/3540), but I fail to generate kubectl docs according to the [doc](https://github.com/kubernetes-incubator/reference-docs#generate-new-kubectl-docs) for reasons:
- `k8s.io/kubernetes/cmd/genkubedocs/gen_kube_docs.go` mentioned in the doc can generate docs for other k8s components except kubectl.
- I find that `k8s.io/kubernetes/cmd/gendocs/gen_kubectl_docs.go` is for kubectl docs generation, but it generates .md files for every command instead of the kubectl.yaml.

@pwittrock Is the doc out of date? or my usage is not correct.

**Comment by pwittrock** [comment]
@supereagle Good catch.  Updated the instructions.  Let me know if they work for you now.

**Comment by supereagle** [comment]
@pwittrock  It works now, thanks. 

The [kubernetes PR 44607](https://github.com/kubernetes/kubernetes/pull/44607) to update kubectl apply doc is merged into master branch, but not cherry-picked into release-1.5 and release-1.6 branch. I am not sure whether there is need to update the `kubectl.yaml` in this repo.

**Comment by pwittrock** [comment]
Yes, you won't see the changes without cherrypicking the change.  I guess you could manually update the kubectl.yaml if we just want to update the docs without cherrypicking the change.

**Comment by supereagle** [comment]
I have submitted the PR #17 to update kubectl.yaml.
