### ISSUE TITLE
Missing name field in Pod example in docs

### ISSUE THREAD

**Issue by edisonxiang** [kubernetes-incubator/reference-docs#33]
**What happened**:
https://kubernetes.io/docs/api-reference/v1.8/#pod-v1-core shows an example of a Pod but the container does not have a name which is a required field (I get an error from kubectl with this example).

**Anything else we need to know?**:  linked with [this issue](https://github.com/kubernetes/kubernetes/issues/55838).

**Environment**:
Kubernetes version (use kubectl version): head

**Comment by adnavare** [comment]
Hi @edisonxiang : Is this issue still open? Are you submitting a new commit?
