### ISSUE TITLE
Mistyped env var in Makefile

### ISSUE THREAD

**Issue by janosi** [kubernetes-incubator/reference-docs#58]
In the Makefile I can see:
cp $(CLISRC)/scroll.js $(**CLEDST**)/scroll.js

I guess, it should be 
cp $(CLISRC)/scroll.js $(**CLIDST**)/scroll.js

Please confirm or correct my understanding!

**Comment by tengqm** [comment]
You are correct.

**Comment by janosi** [comment]
@tengqm @SaphMB I am sorry, I wanted to fix this, but had no time so far :(

**Comment by janosi** [comment]
Closed with https://github.com/kubernetes-incubator/reference-docs/pull/61
/close
